apiVersion: v1
kind: Pod
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld
  namespace: default
spec:
  containers:
  - env:
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    image: ozhankaraman/python-helloworld:4.3.8
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        port: 8080
      initialDelaySeconds: 60
    name: python-helloworld
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        port: 8080
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: python-helloworld
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: python-helloworld
---
